Kap/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Kap.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^kap/|^KAP/', include('KnightsAssistantPlanner.urls')),
)

KnightsAssistantPlanner/forms.py
from KnightsAssistantPlanner.models import events
from django import forms
from django.forms import ModelForm
from KnightsAssistantPlanner.models import workouts
from django.contrib.auth.models import User

class event(forms.ModelForm):
    event_name = forms.CharField(max_length=30)
    month = forms.HiddenInput()
    day = forms.IntegerField()
    year = forms.HiddenInput()
    hour = forms.IntegerField()
    min = forms.IntegerField()
    notes = forms.CharField(max_length=200)
    user = forms.HiddenInput()
    url = forms.HiddenInput()
    class Meta:
        model = events

        fields = ('event_name', 'day', 'hour', 'min', 'notes',)

class workout(ModelForm):
    LARGE = (
        ('CHEST', 'Chest'),
        ('THIGH', 'Thighs'),
        ('UBACK', 'Upper back'),
        ('LBACK', 'Lower back'),
    	)
    SMALL = (
        ('ABS', 'Abdominals'),
        ('TRI', 'Triceps'),
        ('BIC', 'Biceps'),
        ('CAV', 'Calves'),
    	)
    WI = (
        ('LIT', 'Light'),
        ('MED', 'Medium'),
        ('HRD', 'Hard'),
        )
    error_css_class = 'error'

    cal_count = forms.IntegerField()
    large_muscle = forms.ChoiceField(choices=LARGE, required=True)
    small_muscle = forms.ChoiceField(choices=SMALL, required=True)
    intensity = forms.ChoiceField(choices=WI, required=True)
    user = forms.HiddenInput()
    workout = forms.HiddenInput()


    class Meta:
        model = workouts

        fields = ('cal_count', 'large_muscle', 'small_muscle','intensity',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email', 'password')

templates/Daily.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block header %}
<link rel="stylesheet" href={% static "css/daily.css" %}>
<script type="text/javascript" src={% static "js/daily.js" %}></script>
<script>
         $(document).ready(function(){
        $('div.btn.btn-info').click( function() {
                loadPopupBox();
                $("#id_day").val("{{ day }}")
            });

        $('#popupBoxClose').click( function() {
            unloadPopupBox();
        });

        function unloadPopupBox() {    // TO Unload the Popupbox
            $('div#popup_box').fadeOut("slow");
            $("#container").css({ // this is just for style
                "opacity": "1"
            });
        }

        function loadPopupBox() {    // To Load the Popupbox
            $('div#popup_box').fadeIn("slow");
            $("#container").css({ // this is just for style
                "opacity": "0.3"
            });
        }

});
</script>
{% endblock %}
{% block bodyBlock %}

    <meta property="og:url"           content="http://www.your-domain.com/your-page.html" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="Your Website Title" />
    <meta property="og:description"   content="Your description" />
    <meta property="og:image"         content="http://www.your-domain.com/path/image.jpg" />

	<div id="fb-root"></div>
		<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
		fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	</script>
    <div class="table-responsive">
        <div class="col-md-9">
            <h1>{{ day }}-{{ month }}-{{ year }}</h1>
        </div>
        <div class="col-md-2">
            <div class="btn btn-info btn-lg">
                <span id="plus" class="glyphicon glyphicon-plus"></span>
                Add Event
            </div>
        </div>

        <table class="table table-bordered table-hover">
        <tbody>
            <tr>
                <td>
                    All Day Tasks:
                        {% if workout %}
                            <a href="/kap/workout/{{ day }}-{{ month }}-{{ year }}/"> Workout </a>
                        {% endif %}
                </td>
            </tr>
            {% for i in clock %}
                <tr>
                    <td>
                        {{ i }}:00
                        {% for event in event_list %}
                            {% if event.hour == i %}
                                <a href="/kap/event/{{ event.id }}/"><strong> <span class="event_names">{{ event.event_name }}</span></strong></a>
			    	{% if event.url %}
					<div class="fb-share-button pull-right" data-href={{ event.url }} data-layout="button"></div>
                            	{% endif %}
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
    <div id="popup_box">
                <form action={{ actionUrl }} method="post">
                    {% csrf_token %}
                        <table id="form_table">
                            {{ form.as_table }}
                        </table>
                    <input type="submit" value="Submit" />
                </form>
                <a id="popupBoxClose">Close</a>
            </div>
{% endblock %}

templates/Login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block bodyBlock %}
    <body>
        <h1>Login to KAP</h1>

        <form id="login_form" method="post" action="/kap/login/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
<style>
    #logo{
        position:absolute;
        top:50%;
    }
    .knights{
        margin:auto;
        align-content: center;
        color: #2b2b2b;
        text-shadow: 4px 4px 0px rgba(0,0,0,0.1);
        font-size: 600%;
    }
    .knightsColor{
        display:inline-block;
        color:darkgoldenrod;
    }
</style>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    {% block header %}

    {% endblock %}
    <title>{% block titleBlock %} Knights Assistant Planner{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href=" {% static "css/sb-admin.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a  href="/kap/" class="navbar-brand" href="index.html">Knights Assistant Planner</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ user.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li>
                            <a href="/kap/register/"><i class="glyphicon glyphicon-log-in"></i> Register</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="/kap/logout/"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="/KAP/myhealth/"><i class="fa fa-fw fa-child"></i> My Health</a>
                    </li>
                    <li>
                        <a href="/kap/newspage/"><i class="fa fa-fw fa-newspaper-o"></i> UCF News & Events</a>
                    </li>
                    <li>
                        <a href="/kap/mycalendar/"><i class="fa fa-fw fa-calendar"></i> Calendar</a>
                    </li>
                    <li>
                        <a href="/kap/login/"><span class="glyphicon glyphicon-log-in"></span> Log-in</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row" id="bodyWrapper">
                    <div class="col-md-10">
                        {% block bodyBlock %} {% endblock %}
                    </div>
                    <div class="col-md-2" >
                       <img src="{% static "images/KAP Logo.jpg" %}">
                    </div>
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src=" {% static "js/jquery.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
</body>

</html>

templates/calendar.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block header %}
    <link rel="stylesheet" href={% static "css/calendar.css" %}>
    <script>
            $(document).ready(function(){
        $('.day').click( function() {
                loadPopupBox();
                $("#id_year").val("")
            });

        $('#popupBoxClose').click( function() {
            unloadPopupBox();
        });

        function unloadPopupBox() {    // TO Unload the Popupbox
            $('#popup_box').fadeOut("slow");
            $("#container").css({ // this is just for style
                "opacity": "1"
            });
        }

        function loadPopupBox() {    // To Load the Popupbox
            $('#popup_box').fadeIn("slow");
            $("#container").css({ // this is just for style
                "opacity": "0.3"
            });
        }

});
    </script>
{% endblock %}

{% block bodyBlock%}
    <div id="cal">
        <div class="header">
            <span class="left hook"></span>
            <span class="right hook"></span>
            <span class="left button" id="prev"><a class="arrow" href={{ prev }}>&lang;</a></span>
            <span class="right button" id="next"><a class="arrow" href={{ next }}>&rang;</a></span>
            <div id="headerContent">
                <span class="month-year" id="label">{{ monthstr }} {{ yearstr }}</span><!--dynamically add month and year here-->
            </div>
        </div>
        <table id="days">
            <td>sun</td>
            <td>mon</td>
            <td>tue</td>
            <td>wed</td>
            <td>thu</td>
            <td>fri</td>
            <td>sat</td>
        </table>
        <div id="cal-frame">
            <table class="curr">
                <tbody id="calBody"><!--dynamically add the class date, and figure out the starting day of the the loop months days(usearray)-->
                <tr>
                    {% for i in fstDayOfMonth%}
                        <td class="nil"  ></td>
                    {% endfor %}
                    {% for i in leftOver %}
                            <td class="day" >
                                {{ i }}
                                {% for event in event_list %}
                                    {% if event.day == i %}
                                        <a href="/kap/dayView/{{ i }}-{{ month }}-{{ year }}">
                                             <div id="{{ day }}" class="circle"></div>
                                        </a>
                                    {% endif %}
                                {% endfor %}
                                {% for event in workout_list %}
                                    {% if event.day == i %}
                                        <a href="/kap/dayView/{{ i }}-{{ month }}-{{ year }}">
                                             <div id="{{ day }}" class="workout_circle"></div>
                                        </a>
                                    {% endif %}
                                {% endfor %}
                            </td>
                    {% endfor %}
                </tr>
                    {% for day in daysInMonth %}
                        {% if day == startingPoints.0 or day == startingPoints.1 or day == startingPoints.2 or day == startingPoints.3%}
                            <tr>
                                <td class="day">
                                    {{ day }}
                                    {% for event in event_list %}
                                        {% if event.day == day %}
                                            <a href="/kap/dayView/{{ day }}-{{ month }}-{{ year }}">
                                            <div id="{{ day }}" class="circle"></div>
                                        </a>
                                        {% endif %}
                                    {% endfor %}
                                    {% for event in workout_list %}
                                        {% if event.day == day %}
                                            <a href="/kap/dayView/{{ day }}-{{ month }}-{{ year }}">
                                            <div style="background: blue" id="{{ day }}" class="circle"></div>
                                        </a>
                                        {% endif %}
                                    {% endfor %}
                                </td>
                        {% elif day == endingPoints.0 or day == endingPoints.1 or day == endingPoints.2 or day == endingPoints.3%}
                                <td class="day" >
                                    {{ day }}
                                    {% for event in event_list %}
                                        {% if event.day == day %}
                                            <a href="/kap/dayView/{{ day }}-{{ month }}-{{ year }}">
                                                <div id="{{ day }}" class="circle"></div>
                                            </a>
                                        {% endif %}
                                    {% endfor %}
                                    {% for event in workout_list %}
                                        {% if event.day == day %}
                                            <a href="/kap/dayView/{{ day }}-{{ month }}-{{ year }}">
                                                <div style="background: blue" id="{{ day }}" class="circle"></div>
                                            </a>
                                        {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% else  %}
                                <td class="day" >
                                    {{ day }}
                                {% for event in event_list %}
                                    {% if event.day == day %}
                                        <a href="/kap/dayView/{{ day }}-{{ month }}-{{ year }}">
                                            <div id="{{ day }}" class="circle"></div>
                                        </a>
                                    {% endif %}
                                {% endfor %}
                                {% for event in workout_list %}
                                    {% if event.day == day %}
                                        <a href="/kap/dayView/{{ day }}-{{ month }}-{{ year }}">
                                            <div style="background: blue" id="{{ day }}" class="circle"></div>
                                        </a>
                                    {% endif %}
                                {% endfor %}
                                </td>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
            <div id="popup_box">
                <form action={{ actionUrl }} method="post">
                    {% csrf_token %}
                        <table id="form_table">
                            {{ form.as_table }}
                        </table>
                    <input type="submit" value="Submit" />
                </form>
                <a id="popupBoxClose">Close</a>
            </div>
    </div>
{% endblock %}

templates/event.html
{% extends 'base.html' %}

{% block bodyBlock %}
    <div class="col-md-12">
        <table class="table table-hover">
        <thead>
          <tr>
              <th>Event</th>
            <th>{{ event.event_name }}</th>
          </tr>
          <tr>
            <th>Date</th>
            <td>{{ event.month }}/{{ event.day }}/{{ event.year }}</td>
          </tr>
          <tr>
              <th>Time</th>
              <td>{{ event.hour }}:{{ event.min }}</td>
          </tr>
        {% if event.notes %}
            <tr>
              <th>Notes</th>
                <td>{{ event.notes }}</td>
          </tr>
        {% endif %}
        </thead>
    </table>
    </div>
    <div class="col-md-2">
        <button type="button" class="btn btn-primary">Delete</button>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block titleBlock %} My events {%endblock %}

{% block bodyBlock %}
    <div class="col-md-12">
        <h1>
            <strong>
                My Events
            </strong>
        </h1>
    </div>

        <table class="table table-striped">
    <thead>
      <tr>
        <th>Event Name</th>
        <th>Time</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Waka Flocka Concert</td>
        <td>9/3/2015 @ 8 P.M.</td>
        <td>
            Brick squad artist Waka Flocka will be performing live at the UCF arena !
        </td>
      </tr>
      <tr>
        <td>Comedy Night</td>
        <td>9/16/2015 @ 6 P.M.</td>
        <td>
            There will be local Orlando comedians performing in the UCF square out side the arena!
        </td>
      </tr>
      <tr>
        <td>Football Game</td>
        <td>9/19/2015 @ 8 P.M.</td>
        <td>
            Come support UCF's Knights football team while they play against FIU's panthers !
        </td>
      </tr>
    </tbody>
  </table>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block bodyBlock %}
    <body>
        <h1>Login to KAP</h1>

        <form id="login_form" method="post" action="/kap/login/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>
{% endblock %}

templates/myHealth.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block titleBlock %} MyHealth {% endblock %}
<META http-equiv="Content-Script-Type" content="text/tcl">
{% block header %}
<!-- Is this neccessary? Needs Bootstrap -->
    <link rel="stylesheet" href={% static "css/calendar.css" %}>
    <script type="text/javascript" src={% static "js/calendar.js" %}></script>
<!-- Is this neccessary? Needs Bootstrap -->

<script language="Javascript">

</script>
{% endblock %}

{% block bodyBlock %}
    <div class="col-md-4">
        <h1><strong>Health Planner</strong></h1>
    </div>
    <div>
                <form action="/KAP/myhealth" method="post">
                    {% csrf_token %}
                        <table id="form_table">
                            {{ form.as_table }}
                        </table>
                    <input type="submit" value="Submit" />
                </form>
            </div>
{% endblock %}

templates/newspage.html
{% extends 'base.html' %}

{% block titleBlock %} UCF News and Events{% endblock %}

{% block bodyBlock %}
<script src="http://www.google.com/jsapi" type="text/javascript"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
<script src="https://today.ucf.edu/widget/widget.js" type="text/javascript"></script>
<link href="https://today.ucf.edu/widget/style.css" type="text/css" rel="stylesheet"/>
<div class="row">
    <div class="col-md-5">
        <h1>
            <strong>
                UCF Headlines
            </strong>
        </h1>
    </div>
    <div class="col-md-5">
        <h1>
            <strong>
                UCF Events
            </strong>
        </h1>
    </div>
</div>
<div class="row">
    <div class="col-md-5">
        <table class="table table-hover">
            <tbody>
		<div class="today" data-url="https://today.ucf.edu/feed/" data-max="8" data-title="Today"></div>
		<script type="text/javascript">
		$(".today").UCFtoday();
		</script>
            </tbody>
        </table>
    </div>
    <div class="col-md-5">
        <table class="table table-hover">
            <tbody>
		<div class="today" data-url="https://events.ucf.edu/upcoming/feed.rss" data-max="8" data-title="Upcoming"></div>
		<script type="text/javascript">
		$(".today").UCFtoday();
		</script>
            </tbody>
        </table>
    </div>
    <div class="col-md-2">
	<br>
	<br>
	<br>
	<a href="/kap/addEvent/0">Add Event</a>
	<br>
	<br>
	<br>
	<br>
	<a href="/kap/addEvent/1">Add Event</a>
	<br>
	<br>
	<br>
	<br>
	<a href="/kap/addEvent/2">Add Event</a>
	<br>
	<br>
	<br>
	<br>
	<a href="/kap/addEvent/3">Add Event</a>
	<br>
	<br>
	<br>
	<br>
	<a href="/kap/addEvent/4">Add Event</a>
	<br>
	<br>
	<br>
	<br>
	<a href="/kap/addEvent/5">Add Event</a>
	<br>
	<br>
	<br>
	<br>
	<a href="/kap/addEvent/6">Add Event</a>
	<br>
	<br>
	<br>
	<br>
	<a href="/kap/addEvent/7">Add Event</a>
    </div>

</div>

{% endblock %}

templates/register.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
       <title>{% block titleBlock %} Knights Assistant Planner{% endblock %}</title>

</head>
<body>
    <h2> Register </h2>
    {% if registered %}
    Thank you for registering!
    {% else %}
    Register Below!


        <form id="user_form" method="post" action="/KAP/Login/"
                enctype="multipart/form-data">

            {% csrf_token %}


            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}

</body>
</html>
{% load staticfiles %}
{% block header %}
    <head>
        <title>KAP</title>
    </head>
{% endblock %}

{% block bodyBlock %}
        <h1>Register with KAP</h1>
        {% if registered %}
        KAP says: <strong>thank you for registering!</strong>
        <a href="/KAP/">Return to the homepage.</a><br />
        {% else %}
        <form id="user_form" method="post" action="/kap/register/"
                enctype="multipart/form-data">
            {% csrf_token %}
            <table id="form_table">
                {{ user_form.as_table }}
            </table>
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
{% endblock %}

templates/workout.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block bodyBlock %}
    <div class="col-md-12">
        <table class="table table-hover">
        <thead>
          <tr>
            <th>Workout Plan For {{ day }}-{{ month }}-{{ year }}</th>
          </tr>
          <tr>
              <th>{{ Workout.small_muscle }}</th>
            <td>3 x {{ Workout.s_ex }}</td>
          </tr>
          <tr>
              <th>{{ Workout.large_muscle }}</th>
              <td>3 x {{ Workout.l_ex }}</td>
          </tr>
            <tr>
                <th>Abs</th>
                <td>100 x sit-ups</td>
          </tr>
        </thead>
    </table>
    </div>
        <div class="col-md-2">
            <div class="btn btn-info btn-lg">
                <span id="plus" class="glyphicon glyphicon-plus"></span>
                Edit Workout
            </div>
        </div>
{% endblock %}